### ISSUE TITLE
Room Neighbours

### ISSUE THREAD

**Issue by dariank38** [jeremytammik/the_building_coder_samples#1]
Hi,
I was trying to use from
**http://thebuildingcoder.typepad.com/blog/2013/09/room-neighbours.html.**

But I couldn't run the project with the latest version of Revit and got some errors.
So, I tried with the latest version of BuildingCoder from here with the latest version of Revit.
I built without any errors, but I can not see the same result like following.

![image](https://cloud.githubusercontent.com/assets/16154269/21168157/caa3880e-c1ec-11e6-926a-39cb1eb46ec9.png)

How can I get the same result ?

Thanks

Jay

**Comment by jeremytammik** [comment]
i just tested in Revit 2017 with no problems:

![room_neighbours_2017](https://cloud.githubusercontent.com/assets/4264589/21175582/58fdc3c6-c1e3-11e6-81f4-ca514d359382.png)

**Comment by dariank38** [comment]
Thanks for your reply.  
But could you tell me the case and progress to test the project with Revit 2017?
