### ISSUE TITLE
Searching for a method or hint where i can generate multiple collectors each belonging to a different Level by Element Level Filter

### ISSUE THREAD

**Issue by JuhiDesai1910** [jeremytammik/the_building_coder_samples#11]
Just fort he sake of checking Revit's behavior, I manually created collectors which return model groups passing from different levels by their Level Id as a filter. If i just want to make it dynamic by keeping the collector in a loop equal to the count of number of levels we get, is it possible to do so? @jeremytammik

**Comment by JuhiDesai1910** [comment]
public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {
            Document activeDoc = commandData.Application.ActiveUIDocument.Document;
            String view_name = "";


            // Filter views that match the required criteria

            FilteredElementCollector collector

              = new FilteredElementCollector(activeDoc)

                .OfClass(typeof(View));
            ElementClassFilter filter = new ElementClassFilter(typeof(Level));
            

            FilteredElementCollector collector_levels1 = new FilteredElementCollector(activeDoc);
            FilteredElementCollector collector_levels2 = new FilteredElementCollector(activeDoc);
            FilteredElementCollector collector_levels3 = new FilteredElementCollector(activeDoc);
            FilteredElementCollector collector_levels4 = new FilteredElementCollector(activeDoc);
            FilteredElementCollector collector_mg1 = new FilteredElementCollector(activeDoc);
            FilteredElementCollector collector_mg2 = new FilteredElementCollector(activeDoc);
            FilteredElementCollector collector_mg3 = new FilteredElementCollector(activeDoc);
            FilteredElementCollector collector_mg4 = new FilteredElementCollector(activeDoc);
            collector_levels1.WherePasses(filter);
            collector_levels2.WherePasses(filter);
            collector_levels3.WherePasses(filter);
            collector_levels4.WherePasses(filter);
            String level_names = "";
            String mg = "";
            List<String> level_list = new List<String> { };
            foreach (Element l in collector_levels1)
            {
                level_names += l.Name + "," + l.Id;
                level_list.Add(l.Name);
            }
            var query1 = from element in collector_levels1 where element.Name == level_list[0] select element;
            var query2 = from element in collector_levels2 where element.Name == level_list[1] select element;
            var query3 = from element in collector_levels3 where element.Name == level_list[2] select element;
            var query4 = from element in collector_levels3 where element.Name == level_list[2] select element;
            List<Element> level1 = query1.ToList<Element>();
            List<Element> level2 = query2.ToList<Element>();
            List<Element> level3 = query2.ToList<Element>();
            List<Element> level4 = query2.ToList<Element>();
            ElementId levelId1 = level1[0].Id;
            ElementId levelId2 = level2[0].Id;
            ElementId levelId3 = level3[0].Id;
            ElementId levelId4 = level4[0].Id;
            ElementLevelFilter levelFilter1 = new ElementLevelFilter(level_list[0]);
            ElementLevelFilter levelFilter2 = new ElementLevelFilter(level_list[1]);
            ElementLevelFilter levelFilter3 = new ElementLevelFilter(level_list[2]);
            ElementLevelFilter levelFilter4 = new ElementLevelFilter(level_list[3]);
           ICollection<Element> ModelGroupsLevel1 = collector_mg1.OfCategory(BuiltInCategory.OST_IOSModelGroups).WherePasses(levelFilter1).ToElements();
           ICollection<Element> ModelGroupsLevel2 = collector_mg1.OfCategory(BuiltInCategory.OST_IOSModelGroups).WherePasses(levelFilter2).ToElements();
           ICollection<Element> ModelGroupsLevel3 = collector_mg1.OfCategory(BuiltInCategory.OST_IOSModelGroups).WherePasses(levelFilter3).ToElements();
           ICollection<Element> ModelGroupsLevel4 = collector_mg1.OfCategory(BuiltInCategory.OST_IOSModelGroups).WherePasses(levelFilter4).ToElements();
            //Level wise model groups
            
            List<String> mg11=new List<String>();
            List<String> mg21=new List<String>();
           foreach (Element e1 in ModelGroupsLevel1)
            {
             mg11.Add(e1.Name);
             mg += e1.Name +"-"+ e1.LevelId+"\n";
            }

           foreach (Element e2 in ModelGroupsLevel3)
            {
             mg21.Add(e2.Name);
            }
            
            TaskDialog.Show("Hi", mg);
            return Result.Succeeded;
        }
    }
}

**Comment by jeremytammik** [comment]
Please do not misuse the issue submission possibility in this repository to ask general questions. Please direct your question to the Revit API discussion forum instead: https://forums.autodesk.com/t5/revit-api-forum/bd-p/160. Thank you for your understanding and cooperation.
