### ISSUE TITLE
A question about CmdBrepBuilder

### ISSUE THREAD

**Issue by AllenTaiTW** [jeremytammik/the_building_coder_samples#13]
Dear Jeremy,
I have a question about the code (the_building_coder_samples/BuildingCoder/BuildingCoder/CmdBrepBuilder.cs ) at line 41 and line 42.The notation should be front side. ZY plane, X = 100 insdead of front side. ZY plane, X = 0. The front plane is in the positive direction of the x-axis and it's normal points inside the cube. But the top plane and right plane are both in the positive direction of the axis and the normal direction is pointing to the outside of the cube.This confuses me.
Regards, Allen.

**Comment by jeremytammik** [comment]
Dear Allen, your question confuses me. 

The code was developed, tested and shared by my colleagues Ryuji Ogasawara, Angel Velez, Boris Shafiro and John Mitchell. 

Please refer to the original article: 

https://thebuildingcoder.typepad.com/blog/2018/02/directshape-from-brepbuilder-and-boolean.html.

That is all the information I have on it. 

Good luck pondering and understanding this further.
