### ISSUE TITLE
sun vector is reversed 

### ISSUE THREAD

**Issue by cerver** [jeremytammik/the_building_coder_samples#14]
https://github.com/jeremytammik/the_building_coder_samples/blob/f035ad06760475edcddb1e5ea98ca6d4018edaad/BuildingCoder/BuildingCoder/CmdUnrotateNorth.cs#L39

the resulting sun vector is pointing from the ground at the sun and not from the sun at the ground, i recommend reversing the vector at the end before its returned so the resulting vector points in the direction of the sun rays. 

return sunDirection * -1;

**Comment by jeremytammik** [comment]
Thank you for raising this.

Generally, the preferred method for submitting an improvement suggestion such as this is to submit a pull request, not an issue.

In this case, the modification is so minimal that I can apply the modification myself.

In future, if you know the exact solution to an issue, please submit a pull request for it while you are at it anyway.

Thank you!

**Comment by cerver** [comment]
sorry, yes I agree normally i would do a pull request but it was so minor i figured this would be much faster

**Comment by jeremytammik** [comment]
yes, i guess it is. here is the new release implementing your suggestion: https://github.com/jeremytammik/the_building_coder_samples/releases/tag/2021.0.150.19

thank you!
