### ISSUE TITLE
How to test this samples?

### ISSUE THREAD

**Issue by dariank38** [jeremytammik/the_building_coder_samples#2]
Hi, Jeremytammik

I'm new to RevitAPI and this project.
I tried to get the result with the image but I could do like you.
Could you tell me the steps in detail? I want you to give me exact steps like followings.

1) Clone this project 
2) Add to add-in folder
...
I don't know the steps, 

Really looking forward to hear from you.

Best Regards

Jay

**Comment by jeremytammik** [comment]
please work through the Revit API getting started material before we discuss any further: http://thebuildingcoder.typepad.com/blog/about-the-author.html#2 -- thank you!
