### ISSUE TITLE
Restrictions in Material names

### ISSUE THREAD

**Issue by rianby64** [jeremytammik/the_building_coder_samples#4]
Hello Jeremy :smiley: 
I want to set a name to a material, but there're some [restrictions that are undocumented](http://www.revitapidocs.com/2016/683b9b3b-fcd7-299d-e42f-712ac1550f17.htm).

So, here's my test-case
```c#

Material defaultMaterial = new FilteredElementCollector(doc)
  .WherePasses(new ElementClassFilter(typeof(Material)))
  .Where<Element>(e => e.Name.Equals("Default"))
  .FirstOrDefault<Element>() as Material;

String materialName = "Concrete 1:4";
Material createOrUpdateMaterial = new FilteredElementCollector(doc)
  .WherePasses(new ElementClassFilter(typeof(Material)))
  .Where<Element>(e => e.LookupParameter("Name").AsString().Equals(materialName))
  .FirstOrDefault<Element>() as Material;

if (createOrUpdateMaterial == null) {
  createOrUpdateMaterial = defaultMaterial.Duplicate("createorupdate default");

  // Why Revit doesn't accept the ':' char?
  createOrUpdateMaterial.Name = materialName;

  // Why Revit doesn't link the Parameter("Name") with the Property "Name"?
  createOrUpdateMaterial.LookupParameter("Name").SetValueString(materialName);
}
```

- Why Revit doesn't accept the ':' char?
- Why Revit doesn't link the Parameter("Name") with the Property "Name"?
- Does Revit have other restrictions?

I'll be happy if you give me an advice. Thanks a lot, Jeremy!

**Comment by jeremytammik** [comment]
since this has nothing to do with The Building Coder samples, i suggest you raise the question in a new thread in the Revit API discussion forum https://forums.autodesk.com/t5/revit-api-forum/bd-p/160 and i close this as a non-issue. thank you!
