### ISSUE TITLE
How to get the face normal of a referencePlane in familyInstance?

### ISSUE THREAD

**Issue by kingxi82** [jeremytammik/the_building_coder_samples#6]
I looked at the following url, line 77 to 100.
[https://github.com/jeremytammik/the_building_coder_samples/blob/97864c67b86027c3b54824925a690449b6ce593b/BuildingCoder/BuildingCoder/CmdGetDimensionPoints.cs](https://github.com/jeremytammik/the_building_coder_samples/blob/97864c67b86027c3b54824925a690449b6ce593b/BuildingCoder/BuildingCoder/CmdGetDimensionPoints.cs)

FamilyInstance fi=element as FamilyInstance;
Reference ref1 = fi.GetReferenceByName("aName");// a referencePlane  named "aName" in family.
Element el = _rvtDoc.GetElement(ref1.ElementId);
GeometryObject obj = el.GetGeometryObjectFromReference(ref1);
if (obj == null)
{
    MessageBox.Show("code will never be here");
    // element is Grid or ReferencePlane or ??
    ReferencePlane refPl = el as ReferencePlane;
    if (refPl != null) { MessageBox.Show("Yes"); }
    else { MessageBox.Show("NO"); }
}
else
{
    Line l = obj as Line;
    if (l != null) {
        MessageBox.Show("Line");
    }
    PlanarFace f = obj as PlanarFace;
    if (f != null)
    {
        MessageBox.Show("Face");
    }
    Point p = obj as Point;
    if (p != null)
    {
        MessageBox.Show( "P");
    }
//I tried everything, and none of them succeeded.
/*include:
    Curve 
    Edge 
    Face
    GeometryElement 
    GeometryInstance 
    Profile 
    Solid 
    Mesh 
    PolyLine */
}

Is there somewhere I've overlooked?

**Comment by jeremytammik** [comment]
Are you sure that the code listed above is intended to do what you need at all?

It addresses a completely different question here:

http://thebuildingcoder.typepad.com/blog/2017/06/determining-dimension-segment-endoints.html

**Comment by kingxi82** [comment]
Yes,there are real some differences, the "Reference" in your code  is in the project document,  but mine is in family document,and I want to get it in project document. so, mybe it‘s impossible to get a GeometryObject like face that matches the referencePlane in familyInstance.

**Comment by jeremytammik** [comment]
thank you for the explanation. yes, probably.
