### ISSUE TITLE
The sample 'ErrorHandling' may not work with creating ADAPTIVE familyinstance.

### ISSUE THREAD

**Issue by No54** [jeremytammik/the_building_coder_samples#7]
Dear Sir Jeremy,

I find that the IFailuresPreprocessor interface may not catch the warning about same model instance in same position when the creating familyinstance is ADAPTIVE Component Family. 
Look forward to your kind reply.
^_^

**Comment by jeremytammik** [comment]
Dear No54,

Please avoid sending me private messages regarding non-confidential questions that can be shared in public.

I do nothing at all that cannot be shared and published, and share and publish absolutely everything I work on.

I therefore avoid discussing questions like this, and actually all questions whatsoever, one-on-one.

I prefer discussing everything in public and enabling the entire community to contribute and share:

http://thebuildingcoder.typepad.com/blog/about-the-author.html#1

Discussing non-confidential issues in public has several advantages.

- Your peers can join in and help you
- Our conversation becomes visible to others, to help them resolve their issues as well.
- The entire team can help, not just me. Many are more competent than I!

In general, non-confidential Revit API related questions are best discussed in the public Revit API discussion forum:

http://forums.autodesk.com/t5/revit-api/bd-p/160

Thank you!

Best regards

Jeremy

**Comment by No54** [comment]
My fault, so sorry.  - -
