### ISSUE TITLE
press.key method - keyboard shortcut problems in Revit 2019

### ISSUE THREAD

**Issue by eltonrheek** [jeremytammik/the_building_coder_samples#8]
the "cmdpresskey" method worked for me since Revit 2014 - Revit 2018.
I made keyboard shortcuts for many commands like Textnotes, Dimensions.
But, I could not make these keyboard shortcuts work anymore for Revit 2019.
I think the problem could be in these codes:
public class Press
{
  [DllImport( "USER32.DLL" )]
  public static extern bool PostMessage(
    IntPtr hWnd, uint msg, uint wParam, uint lParam );
 
  [DllImport( "user32.dll" )]
  static extern uint MapVirtualKey(
    uint uCode, uint uMapType );
 
  enum WH_KEYBOARD_LPARAM : uint
  {
    KEYDOWN = 0x00000001,
    KEYUP = 0xC0000001
  }
 
  enum KEYBOARD_MSG : uint
  {
    WM_KEYDOWN = 0x100,
    WM_KEYUP = 0x101
  }
 
  enum MVK_MAP_TYPE : uint
  {
    VKEY_TO_SCANCODE = 0,
    SCANCODE_TO_VKEY = 1,
    VKEY_TO_CHAR = 2,
    SCANCODE_TO_LR_VKEY = 3
  }
 
However, I could not resolve this issue.

Jeremy, please help!

Thank you so much for this.

Elton

**Comment by eltonrheek** [comment]
If I put these "press.kes("CS") commands in Ribbons, They are still functional.
But I need them to work in keyboard shortcuts.
What can be the issues for this?

Thank you so much for your help, Jeremy!

Elton

**Comment by jeremytammik** [comment]
does this have anything whatsoever to do with The Building Coder samples? If so, please explain the connection. If not, please move this discussion to the public Revit API discussion forum. Thank you! https://forums.autodesk.com/t5/revit-api-forum/bd-p/160

**Comment by jeremytammik** [comment]
Ok, I see the code now in CmdPressKeys.cs. Sorry for my case sensitivity. The problem is presumably caused by the line

```
       IntPtr revitHandle = System.Diagnostics.Process
        .GetCurrentProcess().MainWindowHandle;
```

Please refer to this explanation:

https://thebuildingcoder.typepad.com/blog/2017/10/modeless-form-keep-revit-focus-and-on-top.html#10

The solution is given here:

https://thebuildingcoder.typepad.com/blog/2018/04/whats-new-in-the-revit-2019-api.html#4.1.4

**Comment by jeremytammik** [comment]
i modified the code to use UiApplication MainWindowHandle to address issue #8 and removed use of JtWindowHandle in release 2019.0.143.10. please test and confirm that it works.

**Comment by eltonrheek** [comment]
Hi Jeremy,
First thank you so much for your help!
The code: press. Keys( hder, "CS") does not work when it comes to keyboard shortcut!
If I put the commands into ribbons, they are working!
But not keyboard shortcuts, which makes me feel Revit 2019 is something strange!!!
All my Press.keys ("CS") keyboard shortcuts are working for all Revit versions except 2019!

I need to press "cs" after I press the assigned keyboard shortcuts to make them work, what could be the issues?
Thanks for your kind input again for helping me with this issue!

Regards,
Elton

**Comment by eltonrheek** [comment]
The keyboard shortcuts (assigned to external commands by the code : press.keys(hdlr, "CS") are still not working even I changed the uniapplication handler as you mentioned! Please help again for this, Jeremy!

**Comment by jeremytammik** [comment]
i am not aware of anything else i can do to help with this. sorry bout that. please raise the topic in the Revit API discussion forum and see whether anyone else has any ideas. thank you. good luck!

**Comment by eltonrheek** [comment]
Thank you so much for all these ideas input,Jeremy !
Have a great day!
Elton
